audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Mattin Noblia
  title:
  license_number:
  about_markdown: |
    I was born in the Basque region of France. Portland reminds me so much of the area where I grew up, that I felt immediately at home as soon as I arrived here. The beauty, culture, and family-friendly environment appeal to me as much as it does to the clients I work with. In addition to residential real estate, I also have a passion for cooking and have owned several food service businesses. You may recognize me from season 6 of Top Chef! But even if you aren’t an aspiring chef, it doesn’t take long to find a great meal here in Portland. My two children love all the fun food carts and ice cream shops but there’s plenty of options for us adults, too. My unique perspective and background have helped me deliver the best possible service to my clients. I make sure I actively listen to your wants and needs, set realistic expectations, and help provide the education and expertise needed to successfully close your transaction. Give me a call today so that I can work to achieve your real estate dreams!
  brand:
  brokerage: MORE Realty
  market:
  address: 14945 SW Sequoia Pkwy 150 Portland, OR 97224
  phone: 503-388-2940
  phone_type:
  phone2:
  phone2_type:
  email: mattin@mattinhomes.com
  url: http://mattinhomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://mattinn.searchnorthwesthomelistings.com/homevalue/default
  second_CTA_text: Home Search
  second_CTA_URL: https://mattinn.searchnorthwesthomelistings.com/search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://mattinn.searchnorthwesthomelistings.com/homevalue/default

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://mattinn.searchnorthwesthomelistings.com/search

lender:
  show_section: true
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name: Vlad Gabor
  license_number:
  company:
  company_license_number:
  phone: 503-380-1636
  email: Vlad.Gabor@onqfinancial.com
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/MattinHomes/
  linkedin_url: https://www.linkedin.com/company/more-realty
  youtube_url: https://www.youtube.com/channel/UCCUGNsy_uFnd9YOMb1kdEqA
  twitter_url: https://twitter.com/homesbymore/
  instagram_url: https://www.instagram.com/mattinway/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Helping families make the right move!
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#00476F'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
